version: "3.8"

services:
  ui:
    image: 'my-org/ui:latest'
    container_name: ui
    ports:
      - 4200:4200
    networks:
      - my-org-network
    restart: on-failure
  backend:
    image: 'my-org/backend-prod:latest'
    container_name: backend
    depends_on: 
      - postgres
    links:
      - postgres:postgres   
    ports:
      - 3333:3333
    networks:
      - my-org-network
    restart: on-failure
    environment: 
      DB_HOSTNAME: postgresql-api
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
  postgres:
    container_name: postgresql-api
    image: postgres:14-alpine
    restart: always
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - my-org-network
networks:
    my-org-network: